name: Cypress Tests

on:
  push:
    branches: [main] # You can specify the branches to trigger the workflow
  workflow_dispatch: # Manually trigger the workflow
  schedule:          # Scheduled cron job
    - cron: '0 0 * * *' # This runs every day at midnight UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 # Use the explicit version number
        with:
          command: npm run cypress:execution
