name: Cypress Tests

on:
  workflow_dispatch:  # Allows manual trigger
    inputs:
      tag:
        description: 'Tag to filter scenarios (e.g., smoke, regression, sample)'
        required: false  # Change to false to allow running without a tag
        default: 'smoke'  # Default value if none is provided
  schedule:           # Sets up a cron job
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          TAG=${{ github.event.inputs.tag }}
          if [ -n "$TAG" ]; then
            echo "Running tests with tag: $TAG"
            npm run cypress:execution-tags --env tags=$TAG  # Run with specified tag
          else
            echo "No tag specified. Running all tests."
            npx cypress run --record --key b4848846-0655-4fb5-9386-b5097124c360  # Adjust as needed for your case
          fi
