name: PR Tests

on: 
  workflow_dispatch:  # Allows manual trigger
jobs:
  pr-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      # Run tests tagged "@smoke"
      # https://github.com/bahmutov/cy-grep
      - name: Smoke tests 💨
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          build: npm run stop-only
          start: npm run start:ci
          # Quote the URL to be safe against YML parsing surprises
          wait-on: 'http://localhost:8888'
          # Run only the tests tagged @smoke
          env: grepTags=@smoke
          # Record the results on the Cypress Dashboard
          record: true
          group: '1 - smoke tests'
          tag: smoke
        # Environment variables while running Cypress
        env:
          # Pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If smoke tests passed, run all the tests
      - name: All E2E tests 🧪
        uses: cypress-io/github-action@v5
        with:
          # We have already installed all dependencies above
          install: false
          # The server is already running
          # Record the results on the Cypress Dashboard
          record: true
          group: '2 - all tests'
        # Environment variables while running Cypress
        env:
          # Pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/bahmutov/find-cypress-specs
      - name: Print test names 🖨
        run: npm run print-tests

      # Confirm the filtering and skipping tests works as expected
      # Using https://github.com/bahmutov/cypress-expect
      - name: Run using grep 🔎
        # All specs without the tests are filtered
        # And all other tests are skipped
        run: |
          npx cypress-expect run \
            --env grep="update state when items are completed" \
            --expect-exactly expected/one.json

      - name: Run using grep tags 🔎
        run: |
          npx cypress-expect run \
            --env grepTags='@misc' \
            --expect-exactly expected/tag-misc.json

      - name: Burn tests 🔥
        run: |
          npx cypress-expect run \
            --env burn=3 \
            --spec cypress/e2e/counter-spec.js \
            --expect-exactly expected/burn-counter.json
